### ISSUE TITLE
Can't Add Private packages

### ISSUE THREAD

**Issue by paulocastroo** [johnnywidth/synopsis-ui#1]
after installing then going to URL: http://localhost:9091/admin
I added a private repo from bit bucket, it didn't do anything after the dialog closed.

**Comment by johnnywidth** [comment]
Do you see added repo after refresh page?

**Comment by planktonfun** [comment]
Yes, is it because the repo I added requires authentication? Is there somewhere I could put my public id_rsa file?

**Comment by johnnywidth** [comment]
No, it is because page not refreshing after added, need fix this bug on frontend side.
About id_rsa, for now it is taken from default path (~/.ssh/id_rsa for linux example).

**Comment by johnnywidth** [comment]
I think i will add custom key path later and this is will be better solution.

**Comment by paulocastroo** [comment]
Awesome thanks

**Comment by johnnywidth** [comment]
@paulocastroo it is difficult change path `~/.ssh/id_rsa` to custom, because i use git commands to clone repositories. So i have two solutions, use docker and add volume to your `~/.ssh/id_rsa` path or add your current `~/.ssh/id_rsa` to github or bitbucket trusted ssh keys.

**Comment by planktonfun** [comment]
Alright I'll just rename my bitbucket key to ~/.ssh/id_rsa
